###
POST https://localhost:7018/api/V01/Authenticate/login
content-type: application/json

{
  "username": "slask",
  "password": "nordin_A1"
}
###
POST https://localhost:7018/api/V01/Authenticate/register
content-type: application/json

{
  "username": "slask",
  "email": "slask@example.com",
  "password": "nordin_A1"
}
###

DELETE https://localhost:7018/api/V01/Authenticate/deleteAuthUserById/050c70d3-6d59-450e-9719-93ac3faf165a

###
GET https://localhost:7018/api/V01/Advert/GetAllAdverts
###
GET https://localhost:7018/api/V01/Advert/GetAdvertById/AE132576-C4D8-4E8A-D5E5-08DAA13F9E8E
###

Post https://localhost:7018/api/V01/Advert/AddAdvert
content-type: application/json

{
  "userId": "60E4E364-15B7-4267-9728-08DAA13F9E82",
  "name": "Monday2",
  "age": 120,
  "race": "string",
  "sex": "string",
  "personallity": "string",
  "rentPeriod": 120,
  "grade": 5,
  "review": "string",
  "imageUrls": "string"
}
###
DELETE https://localhost:7018/api/V01/Advert/DeleteAdvertById/58bd2770-9703-48d1-6610-08daa1401796
###

PATCH  https://localhost:7018/api/V01/Advert/UpdateAdvert/159da9e2-a3ed-4b80-d5ea-08daa13f9e8e
content-type: application/json

{
  "userId": "60e4e364-15b7-4267-9728-08daa13f9e82",
  "name": "Throgg",
  "age": 105,
  "race": "River troll",
  "sex": "Male",
  "personallity": "Will squezze and suck you dry, but not in a good way",
  "rentPeriod": 1,
  "grade": 5,
  "review": "Ohh dear",
  "imageUrls": "https://cdna.artstation.com/p/assets/images/images/036/042/444/large/dong-jin-nam-08.jpg?1616583789"
}
###
GET https://localhost:7018/api/V01/Advert/GetAdvertsByUserId/EE5F173E-57EE-4BA2-9729-08DAA13F9E82

###
GET https://localhost:7018/api/V01/User/GetAllUsers
###
GET https://localhost:7018/api/V01/User/GetUserById/60e4e364-15b7-4267-9728-08daa13f9e82
###
POST https://localhost:7018/api/V01/User/AddUser
content-type: application/json

{
  "alias": "PostUserTest",
  "phoneNr": "string",
  "isLoggedIn": true,
  "profilePictureUrl": "string",
  "authId": "0a1c4914-ec46-4a99-95cf-6326a35994b4"
}

###
DELETE https://localhost:7018/api/V01/User/DeleteUserById/41EFB2E0-7667-4505-457A-08DAA14DD347
###

PATCH  https://localhost:7018/api/V01/User/UpdateUser/FAAC4B71-C8E5-477A-9E0A-08DAA1419869
content-type: application/json

{
  "alias": "PostUserTest2",
  "phoneNr": "string",
  "isLoggedIn": true,
  "profilePictureUrl": "string",
  "authId": "0a1c4914-ec46-4a99-95cf-6326a35994b4"
}

###
