###
POST https://puppy-backend.azurewebsites.net/api/V01/Authenticate/login
content-type: application/json

{
  "username": "jimmy",
  "password": "nordin_A1"
}
###
POST https://puppy-backend.azurewebsites.net/api/V01/Authenticate/register
content-type: application/json

{
  "username": "jimmy2",
  "email": "jimmy2@example.com",
  "password": "nordin_A1"
}
###
GET https://puppy-backend.azurewebsites.net/api/V01/Advert/GetAllAdverts
###
GET https://puppy-backend.azurewebsites.net/api/V01/Advert/GetAdvertById/e253e92d-efd2-40a6-9289-08da9d96df53
###

Post https://puppy-backend.azurewebsites.net/api/V01/Advert/AddAdvert
content-type: application/json

{
  "userId": "32AE3A32-7E2F-410D-1401-08DA9E5DEB4B",
  "name": "NalleKalle",
  "age": 120,
  "race": "string",
  "sex": "string",
  "personallity": "string",
  "rentPeriod": 120,
  "grade": 5,
  "review": "string",
  "imageUrls": "string"
}
###
DELETE https://puppy-backend.azurewebsites.net/api/V01/Advert/DeleteAdvertById/8362AF28-6A6F-41D5-928B-08DA9D96DF53
###
PATCH  https://puppy-backend.azurewebsites.net/api/V01/Advert/UpdateAdvert/AE27D4F0-2404-43E0-E6E1-08DA9E5DEB56
content-type: application/json

{
  "userId": "32AE3A32-7E2F-410D-1401-08DA9E5DEB4B",
  "name": "HejDåDå",
  "age": 120,
  "race": "string",
  "sex": "string",
  "personallity": "string",
  "rentPeriod": 120,
  "grade": 5,
  "review": "string",
  "imageUrls": "string"
}
###
GET https://puppy-backend.azurewebsites.net/api/V01/User/GetAllUsers
###
GET https://puppy-backend.azurewebsites.net/api/V01/User/GetUserById/1ddceaee-95dc-4650-3222-08da9d96df47
###
POST https://puppy-backend.azurewebsites.net/api/V01/User/AddUser
content-type: application/json

{
  "alias": "asdf",
  "email": "asdf@example.com",
  "phoneNr": "string",
  "isLoggedIn": true,
  "profilePictureUrl": "string",
  "adverts": []
}

###
DELETE https://puppy-backend.azurewebsites.net/api/V01/User/DeleteUserById/E2CAEFC4-A65E-4CAD-E5E1-08DA9DAB87C6
###

PATCH  https://puppy-backend.azurewebsites.net/api/V01/User/UpdateUser/DDA0F0EC-7073-4822-3225-08DA9D96DF47
content-type: application/json

{
  "alias": "string",
  "email": "julgran2@example.com",
  "phoneNr": "string",
  "isLoggedIn": true,
  "profilePictureUrl": "string",
  "adverts": [  ]
}

###