###
POST https://puppy-backend.azurewebsites.net/api/V01/Authenticate/login
content-type: application/json

{
  "username": "janbannan",
  "password": "password_A1"
}
###

POST https://puppy-backend.azurewebsites.net/api/V01/Authenticate/login
content-type: application/json

{
  "username": "banjo",
  "password": "Password_A1"
}

###



POST https://puppy-backend.azurewebsites.net/api/V01/Authenticate/register
content-type: application/json

{
  "username": "kalleknut2",
  "email": "kalleknut@example.com",
  "password": "password_A1"
}
###
DELETE https://puppy-backend.azurewebsites.net/api/V01/Authenticate/deleteAuthUserById/322a8943-370e-4190-ac9f-4deccc700cb6

###
GET https://puppy-backend.azurewebsites.net/api/V01/Advert/GetAllAdverts
###
GET https://puppy-backend.azurewebsites.net/api/V01/Advert/GetAdvertById/AE132576-C4D8-4E8A-D5E5-08DAA13F9E8E
###

Post https://puppy-backend.azurewebsites.net/api/V01/Advert/AddAdvert
content-type: application/json

{
  "userId": "A3E46AE9-4695-46E2-CE87-08DAA182F527",
    "name": "Urkel",
    "age": 1,
    "race": "Terrier",
    "sex": "Male",
    "personallity": "Very smart",
    "rentPeriod": 2,
    "grade": 1,
    "review": "",
    "imageUrls": "https://media.istockphoto.com/photos/dog-with-pencil-at-the-office-picture-id667786852?k=20&m=667786852&s=612x612&w=0&h=WuNB1lGE3kq0ZtbJgetKGc5ytxoGY0Hn4CPreT_QEgM="
}
###
DELETE https://puppy-backend.azurewebsites.net/api/V01/Advert/DeleteAdvertById/7F81F817-EA65-4EC4-6611-08DAA1401796
###

PATCH  https://puppy-backend.azurewebsites.net/api/V01/Advert/UpdateAdvert/159da9e2-a3ed-4b80-d5ea-08daa13f9e8e
content-type: application/json

{
  "userId": "A3E46AE9-4695-46E2-CE87-08DAA182F527",
  "name": "Throgg",
  "age": 105,
  "race": "River troll",
  "sex": "Male",
  "personallity": "Likes to cudle",
  "rentPeriod": 1,
  "grade": 5,
  "review": "Ohh dear",
  "imageUrls": "https://cdna.artstation.com/p/assets/images/images/036/042/444/large/dong-jin-nam-08.jpg?1616583789"
}
###
GET https://puppy-backend.azurewebsites.net/api/V01/Advert/GetAdvertsByUserId/EE5F173E-57EE-4BA2-9729-08DAA13F9E82

###
GET https://puppy-backend.azurewebsites.net/api/V01/User/GetAllUsers
###
GET https://puppy-backend.azurewebsites.net/api/V01/User/GetUserById/60e4e364-15b7-4267-9728-08daa13f9e82
###
POST https://puppy-backend.azurewebsites.net/api/V01/User/AddUser
content-type: application/json

{
  "alias": "PostUserTest",
  "phoneNr": "string",
  "isLoggedIn": true,
  "profilePictureUrl": "string",
  "contactEmail": "bannan@gmail.com"
  "authId": "0a1c4914-ec46-4a99-95cf-6326a35994b4"
}

###
DELETE https://puppy-backend.azurewebsites.net/api/V01/User/DeleteUserById/7007DEAA-D939-4E1B-E69F-08DAA17DF0E1
###

PATCH  https://puppy-backend.azurewebsites.net/api/V01/User/UpdateUser/A3E46AE9-4695-46E2-CE87-08DAA182F527
content-type: application/json

{
  "alias": "Kalle",
  "phoneNr": "12345",
  "isLoggedIn": true,
  "profilePictureUrl": "string",
  "authId": "45308519-A643-44A3-8CCB-83C0F7B8E647"
}

###





